Fix Scheduler Process Crash
Removed an extra argument that was being passed to enqueue_periodic_task()

Fixes TypeError: enqueue_periodic_tasks() missing 1 required positional argument: 'start'
In huey/consumer.py line 171 - self.enqueue_periodic_tasks(now)